namespace MovieTelopTranscriber.App.Models;

public sealed record LocalizedUiText(
    string SettingsButton,
    string PathPlaceholder,
    string BrowseButton,
    string ExtractButton,
    string InputSection,
    string SupportedFormats,
    string SettingsSection,
    string FrameInterval,
    string Language,
    string StatusSection,
    string PreviewSection,
    string SyncTimeline,
    string PreviewShell,
    string SelectedItem,
    string Timeline,
    string Results,
    string Activity,
    string RerunFrames,
    string RerunOcr,
    string ExportOnly,
    string LastFailure,
    string SettingsOutputWindowDescription,
    string OcrEngine,
    string CurrentVideo,
    string WorkDirectory,
    string CurrentSettingSummary,
    string OutputDirectory,
    string JsonOutput,
    string SegmentsCsv,
    string FramesCsv,
    string RunLog,
    string RunSummary,
    string LatestResultList,
    string FrameIntervalSettingLabel,
    string FrameIntervalSettingDescription,
    string LanguageSettingDescription,
    string OcrEngineSettingLabel,
    string OcrEngineSettingDescription,
    string OutputSettingLabel,
    string OutputSettingDescription,
    string VideoInfoTitle,
    string VideoInfoDescription,
    string FramesInfoTitle,
    string FramesInfoDescription,
    string OcrInfoTitle,
    string SegmentsInfoTitle,
    string SegmentsInfoDescription,
    string ExportInfoTitle,
    string ExportInfoDescription,
    string LogInfoTitle,
    string LogInfoDescription,
    string WorkInfoTitle,
    string WorkInfoDescription)
{
    public static LocalizedUiText ForLanguage(string code)
    {
        return code switch
        {
            "ja" => Japanese,
            "zh" => Chinese,
            "ko" => Korean,
            _ => English
        };
    }

    public static LocalizedUiText English { get; } = new(
        "Settings",
        "Select a video file or enter a path",
        "Browse",
        "Extract",
        "Input",
        "Supported formats",
        "Settings",
        "Frame interval (sec)",
        "Language",
        "Status",
        "Preview",
        "Sync timeline",
        "Frame extraction shell",
        "Selected item",
        "Timeline",
        "Results",
        "Activity",
        "Rerun frames",
        "Rerun OCR",
        "Export only",
        "Last failure",
        "Adjust language, output folder, and OCR settings. The main window remains available.",
        "OCR engine",
        "Current video",
        "Work directory",
        "Current setting summary",
        "Output directory",
        "JSON",
        "Segments CSV",
        "Frames CSV",
        "Run log",
        "Run summary",
        "Latest result list",
        "Frame interval",
        "Default extraction interval.",
        "Defaults to the OS UI language when it is Japanese, English, Chinese, or Korean.",
        "OCR engine",
        "Set MOVIE_TELOP_OCR_ENGINE=paddleocr to use the PaddleOCR worker, or MOVIE_TELOP_OCR_WORKER for an external JSON worker.",
        "Output",
        "Frames, OCR responses, attributes, logs, and exports are saved under the configured output folder by run.",
        "Video",
        "Current source video",
        "Frames",
        "Extracted frame count",
        "OCR",
        "Segments",
        "Merged telop segments",
        "Export",
        "JSON and CSV output directory",
        "Log",
        "Run log directory",
        "Work",
        "Current output directory");

    private static LocalizedUiText Japanese { get; } = English with
    {
        SettingsButton = "設定",
        PathPlaceholder = "動画ファイルを選択またはパスを入力",
        BrowseButton = "参照",
        ExtractButton = "抽出",
        InputSection = "入力",
        SupportedFormats = "対応形式",
        SettingsSection = "設定",
        FrameInterval = "抽出間隔 (秒)",
        Language = "言語",
        StatusSection = "状態",
        PreviewSection = "プレビュー",
        SyncTimeline = "タイムライン同期",
        PreviewShell = "フレーム抽出プレビュー",
        SelectedItem = "選択項目",
        Timeline = "タイムライン",
        Results = "結果",
        Activity = "処理状況",
        RerunFrames = "フレーム再実行",
        RerunOcr = "OCR 再実行",
        ExportOnly = "出力のみ",
        LastFailure = "直近の失敗",
        SettingsOutputWindowDescription = "言語、出力先フォルダ、OCR 設定を調整できます。メイン画面は引き続き操作できます。",
        OcrEngine = "OCR エンジン",
        CurrentVideo = "現在の動画",
        WorkDirectory = "作業ディレクトリ",
        CurrentSettingSummary = "現在の設定サマリ",
        OutputDirectory = "出力ディレクトリ",
        JsonOutput = "JSON",
        SegmentsCsv = "Segments CSV",
        FramesCsv = "Frames CSV",
        RunLog = "実行ログ",
        RunSummary = "実行サマリ",
        LatestResultList = "直近の結果一覧",
        FrameIntervalSettingLabel = "抽出間隔",
        FrameIntervalSettingDescription = "標準のフレーム抽出間隔です。",
        LanguageSettingDescription = "OS の UI 言語が日本語、英語、中国語、韓国語の場合はその言語を初期選択します。",
        OcrEngineSettingLabel = "OCR エンジン",
        OcrEngineSettingDescription = "PaddleOCR を使う場合は MOVIE_TELOP_OCR_ENGINE=paddleocr、外部 JSON ワーカーを使う場合は MOVIE_TELOP_OCR_WORKER を設定します。",
        OutputSettingLabel = "出力",
        OutputSettingDescription = "フレーム、OCR 応答、属性解析結果、ログ、出力ファイルをラン単位で保存する親フォルダです。",
        VideoInfoTitle = "動画",
        VideoInfoDescription = "現在の入力動画",
        FramesInfoTitle = "フレーム",
        FramesInfoDescription = "抽出済みフレーム数",
        OcrInfoTitle = "OCR",
        SegmentsInfoTitle = "セグメント",
        SegmentsInfoDescription = "統合済みテロップ区間",
        ExportInfoTitle = "出力",
        ExportInfoDescription = "JSON / CSV 出力ディレクトリ",
        LogInfoTitle = "ログ",
        LogInfoDescription = "実行ログディレクトリ",
        WorkInfoTitle = "作業",
        WorkInfoDescription = "現在の出力ディレクトリ"
    };

    private static LocalizedUiText Chinese { get; } = English with
    {
        SettingsButton = "设置",
        PathPlaceholder = "选择视频文件或输入路径",
        BrowseButton = "浏览",
        ExtractButton = "提取",
        InputSection = "输入",
        SupportedFormats = "支持格式",
        SettingsSection = "设置",
        FrameInterval = "帧间隔 (秒)",
        Language = "语言",
        StatusSection = "状态",
        PreviewSection = "预览",
        SyncTimeline = "同步时间轴",
        PreviewShell = "帧提取预览",
        SelectedItem = "选中项目",
        Timeline = "时间轴",
        Results = "结果",
        Activity = "活动",
        RerunFrames = "重新提取帧",
        RerunOcr = "重新执行 OCR",
        ExportOnly = "仅导出",
        LastFailure = "最近失败",
        SettingsOutputWindowDescription = "调整语言、输出文件夹和 OCR 设置。主窗口仍可操作。",
        OcrEngine = "OCR 引擎",
        CurrentVideo = "当前视频",
        WorkDirectory = "工作目录",
        CurrentSettingSummary = "当前设置摘要",
        OutputDirectory = "输出目录",
        SegmentsCsv = "Segments CSV",
        FramesCsv = "Frames CSV",
        RunLog = "运行日志",
        RunSummary = "运行摘要",
        LatestResultList = "最新结果列表",
        FrameIntervalSettingLabel = "帧间隔",
        FrameIntervalSettingDescription = "默认帧提取间隔。",
        LanguageSettingDescription = "当 OS UI 语言为日语、英语、中文或韩语时，默认选择对应语言。",
        OcrEngineSettingLabel = "OCR 引擎",
        OcrEngineSettingDescription = "要使用 PaddleOCR，请设置 MOVIE_TELOP_OCR_ENGINE=paddleocr；要使用外部 JSON worker，请设置 MOVIE_TELOP_OCR_WORKER。",
        OutputSettingLabel = "输出",
        OutputSettingDescription = "帧、OCR 响应、属性结果、日志和导出文件按每次运行保存在此输出文件夹下。",
        VideoInfoTitle = "视频",
        VideoInfoDescription = "当前源视频",
        FramesInfoTitle = "帧",
        FramesInfoDescription = "已提取帧数",
        OcrInfoTitle = "OCR",
        SegmentsInfoTitle = "片段",
        SegmentsInfoDescription = "合并后的字幕片段",
        ExportInfoTitle = "导出",
        ExportInfoDescription = "JSON 和 CSV 输出目录",
        LogInfoTitle = "日志",
        LogInfoDescription = "运行日志目录",
        WorkInfoTitle = "工作",
        WorkInfoDescription = "当前输出目录"
    };

    private static LocalizedUiText Korean { get; } = English with
    {
        SettingsButton = "설정",
        PathPlaceholder = "동영상 파일을 선택하거나 경로를 입력",
        BrowseButton = "찾아보기",
        ExtractButton = "추출",
        InputSection = "입력",
        SupportedFormats = "지원 형식",
        SettingsSection = "설정",
        FrameInterval = "프레임 간격 (초)",
        Language = "언어",
        StatusSection = "상태",
        PreviewSection = "미리보기",
        SyncTimeline = "타임라인 동기화",
        PreviewShell = "프레임 추출 미리보기",
        SelectedItem = "선택 항목",
        Timeline = "타임라인",
        Results = "결과",
        Activity = "작업 상태",
        RerunFrames = "프레임 재실행",
        RerunOcr = "OCR 재실행",
        ExportOnly = "내보내기만",
        LastFailure = "최근 실패",
        SettingsOutputWindowDescription = "언어, 출력 폴더, OCR 설정을 조정합니다. 메인 창은 계속 조작할 수 있습니다.",
        OcrEngine = "OCR 엔진",
        CurrentVideo = "현재 동영상",
        WorkDirectory = "작업 디렉터리",
        CurrentSettingSummary = "현재 설정 요약",
        OutputDirectory = "출력 디렉터리",
        SegmentsCsv = "Segments CSV",
        FramesCsv = "Frames CSV",
        RunLog = "실행 로그",
        RunSummary = "실행 요약",
        LatestResultList = "최근 결과 목록",
        FrameIntervalSettingLabel = "프레임 간격",
        FrameIntervalSettingDescription = "기본 프레임 추출 간격입니다.",
        LanguageSettingDescription = "OS UI 언어가 일본어, 영어, 중국어, 한국어이면 해당 언어를 기본 선택합니다.",
        OcrEngineSettingLabel = "OCR 엔진",
        OcrEngineSettingDescription = "PaddleOCR를 사용하려면 MOVIE_TELOP_OCR_ENGINE=paddleocr를, 외부 JSON worker를 사용하려면 MOVIE_TELOP_OCR_WORKER를 설정합니다.",
        OutputSettingLabel = "출력",
        OutputSettingDescription = "프레임, OCR 응답, 속성 결과, 로그, 내보내기 파일을 실행별로 저장할 상위 폴더입니다.",
        VideoInfoTitle = "동영상",
        VideoInfoDescription = "현재 원본 동영상",
        FramesInfoTitle = "프레임",
        FramesInfoDescription = "추출된 프레임 수",
        OcrInfoTitle = "OCR",
        SegmentsInfoTitle = "세그먼트",
        SegmentsInfoDescription = "병합된 텔롭 구간",
        ExportInfoTitle = "내보내기",
        ExportInfoDescription = "JSON 및 CSV 출력 디렉터리",
        LogInfoTitle = "로그",
        LogInfoDescription = "실행 로그 디렉터리",
        WorkInfoTitle = "작업",
        WorkInfoDescription = "현재 출력 디렉터리"
    };
}
