namespace MovieTelopTranscriber.App.Models;

public sealed record LocalizedUiText(
    string SettingsButton,
    string MenuFile,
    string MenuSettings,
    string MenuView,
    string MenuSelectVideo,
    string MenuStartExtraction,
    string MenuOpenProjectPlanned,
    string MenuSaveProjectPlanned,
    string MenuOpenSettingsWindow,
    string MenuTimelineColumns,
    string PathPlaceholder,
    string BrowseButton,
    string ExtractButton,
    string InputSection,
    string SupportedFormats,
    string SettingsSection,
    string FrameInterval,
    string Language,
    string StatusSection,
    string PreviewSection,
    string SyncTimeline,
    string PreviewPlay,
    string PreviewPause,
    string PreviewShell,
    string SelectedItem,
    string Timeline,
    string TimelineCopy,
    string OpenPathButton,
    string TimelineEdit,
    string TimelineMerge,
    string TimelineSplit,
    string TimelineDelete,
    string TimelineColumnTime,
    string TimelineColumnFrame,
    string TimelineColumnText,
    string TimelineColumnDetail,
    string TimelineColumnFontSize,
    string TimelineColumnConfidence,
    string DeleteTelopTitle,
    string DeleteTelopMessage,
    string DeleteTelopPrimary,
    string DeleteTelopCancel,
    string Results,
    string Activity,
    string RerunFrames,
    string RerunOcr,
    string ExportOnly,
    string LastFailure,
    string ProgressFrameExtraction,
    string ProgressOcr,
    string ProgressFramesUnit,
    string ProgressElapsed,
    string ProgressRemaining,
    string SettingsOutputWindowDescription,
    string OcrEngine,
    string CurrentVideo,
    string WorkDirectory,
    string CurrentSettingSummary,
    string OutputDirectory,
    string JsonOutput,
    string SegmentsCsv,
    string FramesCsv,
    string RunLog,
    string RunSummary,
    string LatestResultList,
    string FrameIntervalSettingLabel,
    string FrameIntervalSettingDescription,
    string LanguageSettingDescription,
    string OcrEngineSettingLabel,
    string OcrEngineSettingDescription,
    string OutputSettingLabel,
    string OutputSettingDescription,
    string OutputFormatsSettingLabel,
    string OutputFormatsSettingDescription,
    string DetectionSettingsTitle,
    string ResetDefaultsButton,
    string PaddlePreprocessSettingTitle,
    string PaddlePreprocessSettingDescription,
    string PaddleDetectionSettingTitle,
    string PaddleDetectionSettingDescription,
    string PaddlePreprocessLabel,
    string PaddlePreprocessDescription,
    string PaddleSharpenLabel,
    string PaddleSharpenDescription,
    string PaddleContrastLabel,
    string PaddleContrastDescription,
    string PaddleTextDetThreshLabel,
    string PaddleTextDetThreshDescription,
    string PaddleTextDetBoxThreshLabel,
    string PaddleTextDetBoxThreshDescription,
    string PaddleTextDetUnclipRatioLabel,
    string PaddleTextDetUnclipRatioDescription,
    string PaddleTextDetLimitSideLenLabel,
    string PaddleTextDetLimitSideLenDescription,
    string PaddleMinTextSizeLabel,
    string PaddleMinTextSizeDescription,
    string PaddleUseTextlineOrientationLabel,
    string PaddleUseTextlineOrientationDescription,
    string PaddleUseDocUnwarpingLabel,
    string PaddleUseDocUnwarpingDescription,
    string SettingDefaultValue,
    string SettingSecondsUnit,
    string VideoInfoTitle,
    string VideoInfoDescription,
    string FramesInfoTitle,
    string FramesInfoDescription,
    string OcrInfoTitle,
    string SegmentsInfoTitle,
    string SegmentsInfoDescription,
    string ExportInfoTitle,
    string ExportInfoDescription,
    string LogInfoTitle,
    string LogInfoDescription,
    string WorkInfoTitle,
    string WorkInfoDescription)
{
    public static LocalizedUiText ForLanguage(string code)
    {
        return code switch
        {
            "ja" => Japanese,
            "zh" => Chinese,
            "ko" => Korean,
            _ => English
        };
    }

    public static LocalizedUiText English { get; } = new(
        "Settings",
        "File",
        "Settings",
        "View",
        "Select video",
        "Start extraction",
        "Open project (planned)",
        "Save project (planned)",
        "Open settings and output",
        "Timeline columns",
        "Select a video file or enter a path",
        "Browse",
        "Extract",
        "Input",
        "Supported formats",
        "Basic settings",
        "Frame interval (sec)",
        "Language",
        "Status",
        "Preview",
        "Sync timeline",
        "Play",
        "Pause",
        "Frame extraction shell",
        "Selected item",
        "Timeline",
        "Copy",
        "Open",
        "Edit",
        "Merge",
        "Split",
        "Delete",
        "Time",
        "Frame",
        "Text",
        "Style",
        "Size",
        "Confidence",
        "Delete telop",
        "Delete the selected telop from the timeline?",
        "Delete",
        "Cancel",
        "Results",
        "Activity",
        "Rerun frames",
        "Rerun OCR",
        "Export only",
        "Last failure",
        "Frame extraction",
        "OCR",
        "frames",
        "elapsed",
        "remaining",
        "Adjust language, output folder, and OCR settings. The main window remains available.",
        "OCR engine",
        "Current video",
        "Work directory",
        "Current setting summary",
        "Output directory",
        "JSON",
        "Segments CSV",
        "Frames CSV",
        "Run log",
        "Run summary",
        "Latest result list",
        "Frame interval",
        "Default extraction interval.",
        "Defaults to the OS UI language when it is Japanese, English, Chinese, or Korean.",
        "OCR engine",
        "Real-video OCR uses PaddleOCR by default. Set MOVIE_TELOP_OCR_ENGINE=json-sidecar only for explicit sidecar validation, or MOVIE_TELOP_OCR_WORKER for an external JSON worker.",
        "Output",
        "Frames, OCR responses, attributes, logs, and exports are saved under the configured output folder by run.",
        "Output formats",
        "Exports JSON, CSV, SRT, VTT, and ASS files from each run.",
        "Detection settings",
        "Reset defaults",
        "PaddleOCR preprocessing",
        "Applies contrast correction and sharpening before OCR without changing scale.",
        "PaddleOCR detection",
        "Adjusts detection thresholds and orientation options. Empty values use PaddleOCR defaults.",
        "Enable OCR preprocessing",
        "Applies contrast correction and sharpening before OCR without changing scale.",
        "Sharpen",
        "Sharpens the frame before OCR to improve small character edges.",
        "Contrast",
        "Contrast correction multiplier before OCR. 1.0 means no correction.",
        "Text detection sensitivity",
        "PaddleOCR text detection threshold.",
        "Detection confidence threshold",
        "PaddleOCR detection box threshold.",
        "Detection box expansion",
        "Expands detected text boxes.",
        "Detection resolution limit",
        "Input side length limit for text detection.",
        "Minimum text size",
        "Filters out detections smaller than this estimated text size.",
        "Textline orientation",
        "Enable when many rotated or vertical text lines are expected.",
        "Document unwarping",
        "Usually keep off for video telops.",
        "default",
        "sec",
        "Video",
        "Current source video",
        "Frames",
        "Extracted frame count",
        "OCR",
        "Segments",
        "Merged telop segments",
        "Export",
        "JSON and CSV output directory",
        "Log",
        "Run log directory",
        "Work",
        "Current output directory");

    private static LocalizedUiText Japanese { get; } = English with
    {
        SettingsButton = "設定",
        MenuFile = "ファイル",
        MenuSettings = "設定",
        MenuView = "表示",
        MenuSelectVideo = "動画を選択",
        MenuStartExtraction = "抽出を開始",
        MenuOpenProjectPlanned = "プロジェクトを開く (今後対応)",
        MenuSaveProjectPlanned = "プロジェクトを保存 (今後対応)",
        MenuOpenSettingsWindow = "設定と出力を開く",
        MenuTimelineColumns = "タイムライン列",
        PathPlaceholder = "動画ファイルを選択またはパスを入力",
        BrowseButton = "参照",
        ExtractButton = "抽出",
        InputSection = "入力",
        SupportedFormats = "対応形式",
        SettingsSection = "基本設定",
        FrameInterval = "抽出間隔 (秒)",
        Language = "言語",
        StatusSection = "状態",
        PreviewSection = "プレビュー",
        SyncTimeline = "タイムライン同期",
        PreviewPlay = "再生",
        PreviewPause = "一時停止",
        PreviewShell = "フレーム抽出プレビュー",
        SelectedItem = "選択項目",
        Timeline = "タイムライン",
        TimelineCopy = "コピー",
        OpenPathButton = "表示",
        TimelineEdit = "編集",
        TimelineMerge = "結合",
        TimelineSplit = "分割",
        TimelineDelete = "削除",
        TimelineColumnTime = "時刻",
        TimelineColumnFrame = "フレーム",
        TimelineColumnText = "テキスト",
        TimelineColumnDetail = "表示属性",
        TimelineColumnFontSize = "サイズ",
        TimelineColumnConfidence = "認識精度",
        DeleteTelopTitle = "テロップを削除",
        DeleteTelopMessage = "選択中のテロップをタイムラインから削除しますか？",
        DeleteTelopPrimary = "削除",
        DeleteTelopCancel = "キャンセル",
        Results = "結果",
        Activity = "処理状況",
        RerunFrames = "フレーム再実行",
        RerunOcr = "OCR 再実行",
        ExportOnly = "出力のみ",
        LastFailure = "直近の失敗",
        ProgressFrameExtraction = "フレーム抽出",
        ProgressOcr = "OCR",
        ProgressFramesUnit = "フレーム",
        ProgressElapsed = "経過時間",
        ProgressRemaining = "残り時間",
        SettingsOutputWindowDescription = "言語、出力先フォルダ、OCR 設定を調整できます。メイン画面は引き続き操作できます。",
        OcrEngine = "OCR エンジン",
        CurrentVideo = "現在の動画",
        WorkDirectory = "作業ディレクトリ",
        CurrentSettingSummary = "現在の設定サマリ",
        OutputDirectory = "出力ディレクトリ",
        JsonOutput = "JSON",
        SegmentsCsv = "Segments CSV",
        FramesCsv = "Frames CSV",
        RunLog = "実行ログ",
        RunSummary = "実行サマリ",
        LatestResultList = "直近の結果一覧",
        FrameIntervalSettingLabel = "抽出間隔",
        FrameIntervalSettingDescription = "標準のフレーム抽出間隔です。",
        LanguageSettingDescription = "OS の UI 言語が日本語、英語、中国語、韓国語の場合はその言語を初期選択します。",
        OcrEngineSettingLabel = "OCR エンジン",
        OcrEngineSettingDescription = "実動画 OCR は既定で PaddleOCR を使います。json-sidecar は sidecar 検証時だけ MOVIE_TELOP_OCR_ENGINE=json-sidecar で明示します。外部 JSON ワーカーは MOVIE_TELOP_OCR_WORKER を設定します。",
        OutputSettingLabel = "出力",
        OutputSettingDescription = "フレーム、OCR 応答、属性解析結果、ログ、出力ファイルをラン単位で保存する親フォルダです。",
        OutputFormatsSettingLabel = "出力形式",
        OutputFormatsSettingDescription = "各ランから JSON、CSV、SRT、VTT、ASS を出力します。",
        DetectionSettingsTitle = "検出設定",
        ResetDefaultsButton = "初期設定に戻す",
        PaddlePreprocessSettingTitle = "PaddleOCR 前処理",
        PaddlePreprocessSettingDescription = "拡大せずにコントラスト補正とシャープ化を適用してから OCR に渡します。",
        PaddleDetectionSettingTitle = "PaddleOCR 検出",
        PaddleDetectionSettingDescription = "検出しきい値や向き補正を設定できます。空欄の値は PaddleOCR の既定値を使います。",
        PaddlePreprocessLabel = "OCR 前処理を有効にする",
        PaddlePreprocessDescription = "拡大せずにコントラスト補正とシャープ化を適用してから OCR に渡します。",
        PaddleSharpenLabel = "シャープ化",
        PaddleSharpenDescription = "小さい文字や細い仮名を認識しやすくするため、OCR 前に画像をシャープ化します。",
        PaddleContrastLabel = "コントラスト",
        PaddleContrastDescription = "OCR 前のコントラスト補正倍率です。1.0 は補正なしです。",
        PaddleTextDetThreshLabel = "文字の見つけやすさ",
        PaddleTextDetThreshDescription = "PaddleOCR の文字検出しきい値です。",
        PaddleTextDetBoxThreshLabel = "検出候補の確からしさ",
        PaddleTextDetBoxThreshDescription = "PaddleOCR の検出ボックスしきい値です。",
        PaddleTextDetUnclipRatioLabel = "検出枠の広げ幅",
        PaddleTextDetUnclipRatioDescription = "検出ボックスの広げ方を調整します。",
        PaddleTextDetLimitSideLenLabel = "検出解像度上限",
        PaddleTextDetLimitSideLenDescription = "検出時の入力画像サイズ上限です。",
        PaddleMinTextSizeLabel = "最小文字サイズ",
        PaddleMinTextSizeDescription = "この推定文字サイズより小さい検出結果を除外します。",
        PaddleUseTextlineOrientationLabel = "文字方向分類",
        PaddleUseTextlineOrientationDescription = "縦書きや回転した文字列が多い場合に試す設定です。",
        PaddleUseDocUnwarpingLabel = "文書ゆがみ補正",
        PaddleUseDocUnwarpingDescription = "撮影文書向けのゆがみ補正です。通常の動画テロップでは OFF を既定にします。",
        SettingDefaultValue = "既定",
        SettingSecondsUnit = "秒",
        VideoInfoTitle = "動画",
        VideoInfoDescription = "現在の入力動画",
        FramesInfoTitle = "フレーム",
        FramesInfoDescription = "抽出済みフレーム数",
        OcrInfoTitle = "OCR",
        SegmentsInfoTitle = "セグメント",
        SegmentsInfoDescription = "統合済みテロップ区間",
        ExportInfoTitle = "出力",
        ExportInfoDescription = "JSON / CSV 出力ディレクトリ",
        LogInfoTitle = "ログ",
        LogInfoDescription = "実行ログディレクトリ",
        WorkInfoTitle = "作業",
        WorkInfoDescription = "現在の出力ディレクトリ"
    };

    private static LocalizedUiText Chinese { get; } = English with
    {
        SettingsButton = "设置",
        MenuFile = "文件",
        MenuSettings = "设置",
        MenuView = "显示",
        MenuSelectVideo = "选择视频",
        MenuStartExtraction = "开始提取",
        MenuOpenProjectPlanned = "打开项目（后续支持）",
        MenuSaveProjectPlanned = "保存项目（后续支持）",
        MenuOpenSettingsWindow = "打开设置和输出",
        MenuTimelineColumns = "时间轴列",
        PathPlaceholder = "选择视频文件或输入路径",
        BrowseButton = "浏览",
        ExtractButton = "提取",
        InputSection = "输入",
        SupportedFormats = "支持格式",
        SettingsSection = "基本设置",
        FrameInterval = "帧间隔 (秒)",
        Language = "语言",
        StatusSection = "状态",
        PreviewSection = "预览",
        SyncTimeline = "同步时间轴",
        PreviewShell = "帧提取预览",
        PreviewPlay = "播放",
        PreviewPause = "暂停",
        SelectedItem = "选中项目",
        Timeline = "时间轴",
        TimelineCopy = "复制",
        OpenPathButton = "打开",
        TimelineEdit = "编辑",
        TimelineMerge = "合并",
        TimelineSplit = "拆分",
        TimelineDelete = "删除",
        TimelineColumnTime = "时间",
        TimelineColumnFrame = "帧",
        TimelineColumnText = "文本",
        TimelineColumnDetail = "显示属性",
        TimelineColumnFontSize = "大小",
        TimelineColumnConfidence = "识别精度",
        DeleteTelopTitle = "删除字幕",
        DeleteTelopMessage = "要从时间轴删除选中的字幕吗？",
        DeleteTelopPrimary = "删除",
        DeleteTelopCancel = "取消",
        Results = "结果",
        Activity = "活动",
        RerunFrames = "重新提取帧",
        RerunOcr = "重新执行 OCR",
        ExportOnly = "仅导出",
        LastFailure = "最近失败",
        ProgressFrameExtraction = "帧提取",
        ProgressOcr = "OCR",
        ProgressFramesUnit = "帧",
        ProgressElapsed = "经过时间",
        ProgressRemaining = "剩余时间",
        SettingsOutputWindowDescription = "调整语言、输出文件夹和 OCR 设置。主窗口仍可操作。",
        OcrEngine = "OCR 引擎",
        CurrentVideo = "当前视频",
        WorkDirectory = "工作目录",
        CurrentSettingSummary = "当前设置摘要",
        OutputDirectory = "输出目录",
        SegmentsCsv = "Segments CSV",
        FramesCsv = "Frames CSV",
        RunLog = "运行日志",
        RunSummary = "运行摘要",
        LatestResultList = "最新结果列表",
        FrameIntervalSettingLabel = "帧间隔",
        FrameIntervalSettingDescription = "默认帧提取间隔。",
        LanguageSettingDescription = "当 OS UI 语言为日语、英语、中文或韩语时，默认选择对应语言。",
        OcrEngineSettingLabel = "OCR 引擎",
        OcrEngineSettingDescription = "实际视频 OCR 默认使用 PaddleOCR。仅在 sidecar 验证时设置 MOVIE_TELOP_OCR_ENGINE=json-sidecar；外部 JSON worker 请设置 MOVIE_TELOP_OCR_WORKER。",
        OutputSettingLabel = "输出",
        OutputSettingDescription = "帧、OCR 响应、属性结果、日志和导出文件按每次运行保存在此输出文件夹下。",
        OutputFormatsSettingLabel = "输出格式",
        OutputFormatsSettingDescription = "每次运行都会导出 JSON、CSV、SRT、VTT 和 ASS 文件。",
        DetectionSettingsTitle = "检测设置",
        ResetDefaultsButton = "重置默认值",
        PaddlePreprocessSettingTitle = "PaddleOCR 预处理",
        PaddlePreprocessSettingDescription = "在不放大帧的情况下，先应用对比度校正和锐化再执行 OCR。",
        PaddleDetectionSettingTitle = "PaddleOCR 检测",
        PaddleDetectionSettingDescription = "调整检测阈值和方向选项。空值使用 PaddleOCR 默认值。",
        PaddlePreprocessLabel = "启用 OCR 预处理",
        PaddlePreprocessDescription = "在不放大帧的情况下，先应用对比度校正和锐化再执行 OCR。",
        PaddleSharpenLabel = "锐化",
        PaddleSharpenDescription = "在 OCR 前锐化图像，以改善小字符和细字符边缘。",
        PaddleContrastLabel = "对比度",
        PaddleContrastDescription = "OCR 前的对比度校正倍率。1.0 表示不校正。",
        PaddleTextDetThreshLabel = "文字检测灵敏度",
        PaddleTextDetThreshDescription = "PaddleOCR 文本检测阈值。",
        PaddleTextDetBoxThreshLabel = "检测结果可信度",
        PaddleTextDetBoxThreshDescription = "PaddleOCR 检测框阈值。",
        PaddleTextDetUnclipRatioLabel = "检测框扩展量",
        PaddleTextDetUnclipRatioDescription = "调整检测框扩展量。",
        PaddleTextDetLimitSideLenLabel = "检测分辨率上限",
        PaddleTextDetLimitSideLenDescription = "文本检测时的输入边长上限。",
        PaddleMinTextSizeLabel = "最小文字大小",
        PaddleMinTextSizeDescription = "过滤掉估计文字大小低于此值的检测结果。",
        PaddleUseTextlineOrientationLabel = "文本方向分类",
        PaddleUseTextlineOrientationDescription = "当旋转或竖排文本较多时可尝试启用。",
        PaddleUseDocUnwarpingLabel = "文档畸变校正",
        PaddleUseDocUnwarpingDescription = "面向拍摄文档的畸变校正。普通视频字幕通常保持关闭。",
        SettingDefaultValue = "默认",
        SettingSecondsUnit = "秒",
        VideoInfoTitle = "视频",
        VideoInfoDescription = "当前源视频",
        FramesInfoTitle = "帧",
        FramesInfoDescription = "已提取帧数",
        OcrInfoTitle = "OCR",
        SegmentsInfoTitle = "片段",
        SegmentsInfoDescription = "合并后的字幕片段",
        ExportInfoTitle = "导出",
        ExportInfoDescription = "JSON 和 CSV 输出目录",
        LogInfoTitle = "日志",
        LogInfoDescription = "运行日志目录",
        WorkInfoTitle = "工作",
        WorkInfoDescription = "当前输出目录"
    };

    private static LocalizedUiText Korean { get; } = English with
    {
        SettingsButton = "설정",
        MenuFile = "파일",
        MenuSettings = "설정",
        MenuView = "보기",
        MenuSelectVideo = "동영상 선택",
        MenuStartExtraction = "추출 시작",
        MenuOpenProjectPlanned = "프로젝트 열기 (추후 지원)",
        MenuSaveProjectPlanned = "프로젝트 저장 (추후 지원)",
        MenuOpenSettingsWindow = "설정 및 출력 열기",
        MenuTimelineColumns = "타임라인 열",
        PathPlaceholder = "동영상 파일을 선택하거나 경로를 입력",
        BrowseButton = "찾아보기",
        ExtractButton = "추출",
        InputSection = "입력",
        SupportedFormats = "지원 형식",
        SettingsSection = "기본 설정",
        FrameInterval = "프레임 간격 (초)",
        Language = "언어",
        StatusSection = "상태",
        PreviewSection = "미리보기",
        SyncTimeline = "타임라인 동기화",
        PreviewShell = "프레임 추출 미리보기",
        PreviewPlay = "재생",
        PreviewPause = "일시정지",
        SelectedItem = "선택 항목",
        Timeline = "타임라인",
        TimelineCopy = "복사",
        OpenPathButton = "열기",
        TimelineEdit = "편집",
        TimelineMerge = "병합",
        TimelineSplit = "분할",
        TimelineDelete = "삭제",
        TimelineColumnTime = "시간",
        TimelineColumnFrame = "프레임",
        TimelineColumnText = "텍스트",
        TimelineColumnDetail = "표시 속성",
        TimelineColumnFontSize = "크기",
        TimelineColumnConfidence = "인식 정확도",
        DeleteTelopTitle = "텔롭 삭제",
        DeleteTelopMessage = "선택한 텔롭을 타임라인에서 삭제할까요?",
        DeleteTelopPrimary = "삭제",
        DeleteTelopCancel = "취소",
        Results = "결과",
        Activity = "작업 상태",
        RerunFrames = "프레임 재실행",
        RerunOcr = "OCR 재실행",
        ExportOnly = "내보내기만",
        LastFailure = "최근 실패",
        ProgressFrameExtraction = "프레임 추출",
        ProgressOcr = "OCR",
        ProgressFramesUnit = "프레임",
        ProgressElapsed = "경과 시간",
        ProgressRemaining = "남은 시간",
        SettingsOutputWindowDescription = "언어, 출력 폴더, OCR 설정을 조정합니다. 메인 창은 계속 조작할 수 있습니다.",
        OcrEngine = "OCR 엔진",
        CurrentVideo = "현재 동영상",
        WorkDirectory = "작업 디렉터리",
        CurrentSettingSummary = "현재 설정 요약",
        OutputDirectory = "출력 디렉터리",
        SegmentsCsv = "Segments CSV",
        FramesCsv = "Frames CSV",
        RunLog = "실행 로그",
        RunSummary = "실행 요약",
        LatestResultList = "최근 결과 목록",
        FrameIntervalSettingLabel = "프레임 간격",
        FrameIntervalSettingDescription = "기본 프레임 추출 간격입니다.",
        LanguageSettingDescription = "OS UI 언어가 일본어, 영어, 중국어, 한국어이면 해당 언어를 기본 선택합니다.",
        OcrEngineSettingLabel = "OCR 엔진",
        OcrEngineSettingDescription = "실제 동영상 OCR은 기본적으로 PaddleOCR를 사용합니다. sidecar 검증 시에만 MOVIE_TELOP_OCR_ENGINE=json-sidecar를 명시하고, 외부 JSON worker는 MOVIE_TELOP_OCR_WORKER를 설정합니다.",
        OutputSettingLabel = "출력",
        OutputSettingDescription = "프레임, OCR 응답, 속성 결과, 로그, 내보내기 파일을 실행별로 저장할 상위 폴더입니다.",
        OutputFormatsSettingLabel = "출력 형식",
        OutputFormatsSettingDescription = "각 실행에서 JSON, CSV, SRT, VTT, ASS 파일을 내보냅니다.",
        DetectionSettingsTitle = "검출 설정",
        ResetDefaultsButton = "기본값으로 재설정",
        PaddlePreprocessSettingTitle = "PaddleOCR 전처리",
        PaddlePreprocessSettingDescription = "확대 없이 대비 보정과 선명화를 적용한 뒤 OCR에 전달합니다.",
        PaddleDetectionSettingTitle = "PaddleOCR 검출",
        PaddleDetectionSettingDescription = "검출 임계값과 방향 옵션을 조정합니다. 빈 값은 PaddleOCR 기본값을 사용합니다.",
        PaddlePreprocessLabel = "OCR 전처리 사용",
        PaddlePreprocessDescription = "확대 없이 대비 보정과 선명화를 적용한 뒤 OCR에 전달합니다.",
        PaddleSharpenLabel = "선명화",
        PaddleSharpenDescription = "작은 글자와 얇은 글자의 가장자리를 개선하기 위해 OCR 전에 이미지를 선명화합니다.",
        PaddleContrastLabel = "대비",
        PaddleContrastDescription = "OCR 전 대비 보정 배율입니다. 1.0은 보정 없음입니다.",
        PaddleTextDetThreshLabel = "문자 검출 민감도",
        PaddleTextDetThreshDescription = "PaddleOCR 텍스트 검출 임계값입니다.",
        PaddleTextDetBoxThreshLabel = "검출 결과 신뢰도",
        PaddleTextDetBoxThreshDescription = "PaddleOCR 검출 박스 임계값입니다.",
        PaddleTextDetUnclipRatioLabel = "검출 박스 확장량",
        PaddleTextDetUnclipRatioDescription = "검출 박스 확장 정도를 조정합니다.",
        PaddleTextDetLimitSideLenLabel = "검출 해상도 상한",
        PaddleTextDetLimitSideLenDescription = "텍스트 검출 입력 이미지의 한 변 길이 제한입니다.",
        PaddleMinTextSizeLabel = "최소 문자 크기",
        PaddleMinTextSizeDescription = "추정 문자 크기가 이 값보다 작은 검출 결과를 제외합니다.",
        PaddleUseTextlineOrientationLabel = "문자 방향 분류",
        PaddleUseTextlineOrientationDescription = "회전되거나 세로인 텍스트가 많을 때 시도하는 설정입니다.",
        PaddleUseDocUnwarpingLabel = "문서 왜곡 보정",
        PaddleUseDocUnwarpingDescription = "촬영 문서용 왜곡 보정입니다. 일반 동영상 텔롭에서는 보통 꺼 둡니다.",
        SettingDefaultValue = "기본값",
        SettingSecondsUnit = "초",
        VideoInfoTitle = "동영상",
        VideoInfoDescription = "현재 원본 동영상",
        FramesInfoTitle = "프레임",
        FramesInfoDescription = "추출된 프레임 수",
        OcrInfoTitle = "OCR",
        SegmentsInfoTitle = "세그먼트",
        SegmentsInfoDescription = "병합된 텔롭 구간",
        ExportInfoTitle = "내보내기",
        ExportInfoDescription = "JSON 및 CSV 출력 디렉터리",
        LogInfoTitle = "로그",
        LogInfoDescription = "실행 로그 디렉터리",
        WorkInfoTitle = "작업",
        WorkInfoDescription = "현재 출력 디렉터리"
    };
}
